name: Publicar pacote

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  publish:
    name: Publicar pacote
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Instalar o Auto Release
        run: dotnet tool install -g autorelease

      - name: Criar notas da release
        id: release_note
        run: |
          echo "NOTE<<EOF" >> "$GITHUB_OUTPUT"
          autorelease note --token ${{ secrets.GITHUB_TOKEN }} --repo ${{ github.repository }} >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Criar versão da release
        id: release_version
        run: echo "VERSION=$(autorelease version --token ${{ secrets.GITHUB_TOKEN }} --repo ${{ github.repository }})" >> "$GITHUB_OUTPUT"

      - name: Obter data atual
        id: release_date
        run: echo "DATE=$(date +%Y-%m-%d)" >> "$GITHUB_OUTPUT"

      - name: Criar release no GitHub
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.release_version.outputs.VERSION }}
          release_name: $Auto Release v${{ steps.release_version.outputs.VERSION }} (${{ steps.release_date.outputs.DATE }})
          body: ${{ steps.release_note.outputs.NOTE }}
          draft: false
          prerelease: false

      - name: Restaurar dependências
        run: dotnet restore

      - name: Gerar pacote
        run: dotnet pack

      - name: Carregar o pacote no NuGet
        run: |
          cd published/
          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate

      - name: Carregar o pacote no GitHub
        run: |
          cd published/
          dotnet nuget push *.nupkg --api-key ${{ secrets.PACKAGE_TOKEN }} --source "https://nuget.pkg.github.com/kempdec/index.json" --skip-duplicate