name: Publicar pacote

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  publish:
    name: Publicar pacote
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Instalar o Auto Release
        run: dotnet tool install -g autorelease

      - name: Criar release no GitHub
        id: release
        env:
          AutoRelease_Token: ${{ secrets.GITHUB_TOKEN }}
          AutoRelease_Repo: ${{ github.repository }}
        run: echo "VERSION=$(autorelease create)" >> "$GITHUB_OUTPUT"

      - name: Restaurar dependências
        run: dotnet restore

      - name: Gerar pacote
        run: dotnet pack -p:PackageVersion=${{ steps.release.outputs.VERSION }}

      - name: Carregar o pacote no NuGet
        run: |
          cd published/
          dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate

      - name: Carregar o pacote no GitHub
        run: |
          cd published/
          dotnet nuget push *.nupkg --api-key ${{ secrets.PACKAGE_TOKEN }} --source "https://nuget.pkg.github.com/kempdec/index.json" --skip-duplicate